package com.evin.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EVIN_LINK".
 */
public class EvinLink {

    /**
     * 开始位置
     */
    private int start;
    /**
     * 结束位置
     */
    private int end;
    /**
     * 跳转类型
     * 网址 id等
     */
    private int type;
    /**
     * url
     */
    private String path;
    /** Not-null value. */
    /**
     * 显示文字
     */
    private String text;

    public EvinLink() {
    }

    public EvinLink(int start, int end, int type, String path, String text) {
        this.start = start;
        this.end = end;
        this.type = type;
        this.path = path;
        this.text = text;
    }

    public int getStart() {
        return start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public int getEnd() {
        return end;
    }

    public void setEnd(int end) {
        this.end = end;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

}
