package com.evin.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EVIN_TIME".
 */
public class EvinTime {

    private Long id;
    /**
     * 公元前后
     * true  公元前
     * false  公元后
     */
    private Boolean bcTime;
    /**
     * 公元后有效(时间戳)
     */
    private long timeStamp;
    /**
     * 上传时间
     */
    private long timeUpload;
    /**
     * 年份时间
     * 公元前为负数 如-199年
     */
    private int timeYear;
    /**
     * 时间字符串表达格式
     * 如 前1995年10月14日
     */
    private String timeString;

    public EvinTime() {
    }

    public EvinTime(Long id) {
        this.id = id;
    }

    public EvinTime(Long id, Boolean bcTime, long timeStamp, long timeUpload, int timeYear, String timeString) {
        this.id = id;
        this.bcTime = bcTime;
        this.timeStamp = timeStamp;
        this.timeUpload = timeUpload;
        this.timeYear = timeYear;
        this.timeString = timeString;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getBcTime() {
        return bcTime;
    }

    public void setBcTime(Boolean bcTime) {
        this.bcTime = bcTime;
    }

    public long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(long timeStamp) {
        this.timeStamp = timeStamp;
    }

    public long getTimeUpload() {
        return timeUpload;
    }

    public void setTimeUpload(long timeUpload) {
        this.timeUpload = timeUpload;
    }

    public int getTimeYear() {
        return timeYear;
    }

    public void setTimeYear(int timeYear) {
        this.timeYear = timeYear;
    }

    public String getTimeString() {
        return timeString;
    }

    public void setTimeString(String timeString) {
        this.timeString = timeString;
    }

}
